GET http://localhost:8080/product
Content-Type: application/json



####
POST http://localhost:8080/product
Content-Type: application/json

{
  "product_id": 20,
  "product_name": "Atorvastatina",
  "quantity": 120,
  "price": 85,
  "description": "Sirve para reducir los niveles de trigliricéridos ",
  "provider_id": 1
}


####
DELETE http://localhost:8080/product/20
Content-Type: application/json

####
GET http://localhost:8080/product/14
Content-Type: application/json


####
PUT http://localhost:8080/product
Content-Type: application/json

{
  "id_product": 14,
  "name_product": "Paracetamol",
  "price": 8.7,
  "quantity": 120,
  "description": "para aliviar la fiebre y el dolor",
  "provider_id": 2
}



