GET http://localhost:8092/product
Content-Type: application/json



####
POST http://localhost:8092/product
Content-Type: application/json

{
  "product_id": 20,
  "product_name": "Atorvastatina",
  "quantity": 120,
  "price": 85,
  "description": "Sirve para reducir los niveles de trigliricéridos ",
  "provider_id": 1
}


####
DELETE http://localhost:8092/product/20
Content-Type: application/json

####
GET http://localhost:8092/product/50
Content-Type: application/json




###Gateway
GET http://localhost:8093/ms-products/product
Content-Type: application/json


####
POST http://localhost:8093/ms-products/product
Content-Type: application/json

{
  "product_id": 14,
  "product_name": "Atorvastatina",
  "quantity": 120,
  "price": 85,
  "description": "Sirve para reducir los niveles de trigliricéridos ",
  "provider_id": 1
}


####
DELETE http://localhost:8093/ms-products/product/14
Content-Type: application/json

####
GET http://localhost:8093/ms-products/product/1
Content-Type: application/json















